name: s3_client

description: Dart AWS S3 client library

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  http: ^1.2.2
  amazon_cognito_identity_dart_2: ^3.6.5
  recase: ^4.1.0
  path: ^1.9.0
  mime: ^1.0.6
