name: app_content

description: Dart package which manages the content in the app.
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  api_client:
    path: ../api_client
  app_storage:
    path: ../app_storage
  dio: ^5.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
