// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9atmostllLcrHE0p_YGXhSmaXQ_GQ9SA',
    appId: '1:155948170401:android:feaf8c5095710ced66c4e0',
    messagingSenderId: '155948170401',
    projectId: 'flutter-template-b6f33',
    storageBucket: 'flutter-template-b6f33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClWlvl1cu0zdXy3Q6cytkrvLnt5TTjwA0',
    appId: '1:155948170401:ios:2d853053915e821566c4e0',
    messagingSenderId: '155948170401',
    projectId: 'flutter-template-b6f33',
    storageBucket: 'flutter-template-b6f33.firebasestorage.app',
    iosBundleId: 'app.net17.staging',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC9TA8-JlWlG1T1bTUz6rPFqiD64YWcrc',
    appId: '1:155948170401:web:f2e8ae995b9ab9f066c4e0',
    messagingSenderId: '155948170401',
    projectId: 'flutter-template-b6f33',
    authDomain: 'flutter-template-b6f33.firebaseapp.com',
    storageBucket: 'flutter-template-b6f33.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClWlvl1cu0zdXy3Q6cytkrvLnt5TTjwA0',
    appId: '1:155948170401:ios:c4e00c0e4a3d04c366c4e0',
    messagingSenderId: '155948170401',
    projectId: 'flutter-template-b6f33',
    storageBucket: 'flutter-template-b6f33.firebasestorage.app',
    iosBundleId: 'com.example.tradeJournal',
  );

}