// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuRAUqf-B0C0YsudbI5yovSe0gsKxUhxc',
    appId: '1:551068958386:web:fa15b4bdf870ea9a0853ab',
    messagingSenderId: '551068958386',
    projectId: 'circled-66a51',
    authDomain: 'circled-66a51.firebaseapp.com',
    storageBucket: 'circled-66a51.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaGd2L5hjFRvjungDe_NbJA1gSA6LXcyo',
    appId: '1:551068958386:android:4c9c832814ca5be90853ab',
    messagingSenderId: '551068958386',
    projectId: 'circled-66a51',
    storageBucket: 'circled-66a51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmp1CIDSVK78QyKNKjRSDnAmkXEYcu9KE',
    appId: '1:551068958386:ios:0f1bb8afbc4151d70853ab',
    messagingSenderId: '551068958386',
    projectId: 'circled-66a51',
    storageBucket: 'circled-66a51.firebasestorage.app',
    iosBundleId: 'com.template.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmp1CIDSVK78QyKNKjRSDnAmkXEYcu9KE',
    appId: '1:551068958386:ios:f0936a67300355f30853ab',
    messagingSenderId: '551068958386',
    projectId: 'circled-66a51',
    storageBucket: 'circled-66a51.firebasestorage.app',
    iosBundleId: 'com.example.tradeJournal',
  );
}