name: app_authentication

description: Dart package which manages the authentication in the app.
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  app_storage:
    path: ../app_storage
  app_logger:
    path: ../app_logger
  api_client:
    path: ../api_client
  json_annotation: ^4.9.0
  bloc: ^9.0.0
  equatable: ^2.0.5
